# Generated by Django 3.0.8 on 2020-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200723_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronec',
            name='wayforbd',
            field=models.CharField(max_length=128, verbose_name='Путь к базе данных'),
        ),
    ]
