# Generated by Django 3.0.8 on 2020-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200724_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormToOneC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workobj', models.CharField(max_length=256)),
                ('job', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
            ],
        ),
    ]
