# Generated by Django 3.0.8 on 2020-08-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_multiformonec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiformonec',
            old_name='job',
            new_name='job2',
        ),
        migrations.RenameField(
            model_name='multiformonec',
            old_name='kol',
            new_name='kol2',
        ),
        migrations.RenameField(
            model_name='multiformonec',
            old_name='time',
            new_name='time2',
        ),
    ]
