# Generated by Django 3.0.8 on 2020-08-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200804_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiFormOneC',
        ),
    ]
