# Generated by Django 3.0.8 on 2020-08-05 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_delete_multiformonec'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiFormOneC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job2', models.CharField(max_length=256)),
                ('time2', models.CharField(max_length=8)),
                ('kol2', models.CharField(max_length=8)),
                ('formtoonec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FormToOneC')),
            ],
        ),
    ]
