# Generated by Django 3.0.8 on 2020-08-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_multiformonec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtoonec',
            name='job',
        ),
        migrations.RemoveField(
            model_name='formtoonec',
            name='kol',
        ),
        migrations.RemoveField(
            model_name='formtoonec',
            name='time',
        ),
    ]
