# Generated by Django 3.0.8 on 2020-08-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200807_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiformonec',
            name='job2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='multiformonec',
            name='kol2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='multiformonec',
            name='time2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
