# Generated by Django 3.0.8 on 2020-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200815_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtoonec',
            name='job2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='formtoonec',
            name='kol2',
            field=models.IntegerField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='formtoonec',
            name='time2',
            field=models.IntegerField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='formtoonec',
            name='workobj',
            field=models.CharField(max_length=1000),
        ),
    ]
