# Generated by Django 3.0.8 on 2020-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200815_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtoonec',
            name='job2',
            field=models.CharField(default='', max_length=1000, verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='formtoonec',
            name='kol2',
            field=models.IntegerField(default='', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='formtoonec',
            name='time2',
            field=models.IntegerField(default='', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='formtoonec',
            name='workobj',
            field=models.CharField(max_length=1000, verbose_name='Тип работы'),
        ),
    ]
