# Generated by Django 3.0.8 on 2020-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200815_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtoonec',
            name='id_user',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='formtoonec',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
