# Generated by Django 3.0.8 on 2020-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200815_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtoonec',
            name='userid2',
            field=models.CharField(default='', max_length=200, verbose_name='ID'),
        ),
    ]
