# Generated by Django 3.0.8 on 2020-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_formtoonec_usernameonec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtoonec',
            name='workobj',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Тип работы'),
        ),
    ]
