# Generated by Django 3.0.8 on 2020-08-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200817_1153'),
        ('mainapp', '0018_auto_20200816_1017'),
    ]

    operations = [
    ]
