# Generated by Django 3.0.8 on 2020-08-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_merge_20200818_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtoonec',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='formtoonec',
            name='username',
        ),
    ]
