# Generated by Django 3.1 on 2020-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20200818_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtoonec',
            name='passwordforonec2',
            field=models.CharField(default='', max_length=64, verbose_name='Пароль пользователя 1С'),
        ),
    ]
