# Generated by Django 3.1 on 2020-08-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_formtoonec_passwordforonec2'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtoonec',
            name='comments',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
    ]
