# Generated by Django 3.1 on 2020-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20200825_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allperiod', models.CharField(max_length=500, verbose_name='All')),
                ('week', models.CharField(max_length=500, verbose_name='week')),
                ('month', models.CharField(max_length=500, verbose_name='month')),
            ],
        ),
    ]
