# Generated by Django 3.1 on 2020-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_report_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.CharField(default='', max_length=500, verbose_name='iduser')),
                ('allperiod', models.CharField(max_length=500, verbose_name='All')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.CharField(max_length=500, verbose_name='iduser')),
                ('month', models.CharField(max_length=500, verbose_name='month')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.CharField(default='', max_length=500, verbose_name='iduser')),
                ('week', models.CharField(max_length=500, verbose_name='week')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
