# Generated by Django 3.1 on 2020-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20200829_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=500, verbose_name='username')),
                ('password', models.CharField(default='', max_length=500, verbose_name='password')),
                ('iduser', models.CharField(max_length=500, verbose_name='iduser')),
                ('lastweek', models.CharField(max_length=500, verbose_name='LastWeek')),
            ],
        ),
    ]
