# Generated by Django 3.1 on 2020-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_lastweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='allper',
            name='wayforbd',
            field=models.CharField(default='', max_length=500, verbose_name='Путь к базе данных'),
        ),
        migrations.AddField(
            model_name='formtoonec',
            name='wayforbd',
            field=models.CharField(default='', max_length=500, verbose_name='Путь к базе данных'),
        ),
        migrations.AddField(
            model_name='lastweek',
            name='wayforbd',
            field=models.CharField(default='', max_length=500, verbose_name='Путь к базе данных'),
        ),
        migrations.AddField(
            model_name='month',
            name='wayforbd',
            field=models.CharField(default='', max_length=500, verbose_name='Путь к базе данных'),
        ),
        migrations.AddField(
            model_name='week',
            name='wayforbd',
            field=models.CharField(default='', max_length=500, verbose_name='Путь к базе данных'),
        ),
    ]
